//// Tables

Table project {
  id int [pk, not null]
  name varchar
  
  created_at datetime [not null]
  last_synced_at datetime
  status varchar [not null]

  github_repository_id bigint [unique, not null]
  repository_owner varchar [not null]
  repository_name varchar [not null]

  selected_version_id int
}

Table project_version {
  id int [pk, not null]
  project_id int [not null]

  branch varchar [not null]
  commit_hash varchar [not null]

  analysis_status varchar [not null]
  analyzed_at datetime

  indexes {
    (project_id, commit_hash) [unique]
  }
}

Table evaluation {
  id int [pk, not null]
  project_version_id int [not null]

  type varchar [not null]

  created_at datetime [not null]
  started_at datetime
  finished_at datetime
}

Table agent_execution {
  id int [pk, not null]
  evaluation_id int [not null]
  agent_type varchar [not null]
  status varchar [not null]
  created_at datetime [not null]
  started_at datetime
  finished_at datetime
  input_tokens int
  output_tokens int
  error text
}

Table ai_provider {
  id int [pk, not null]
  name varchar [not null]
}

Table ai_credential {
  id int [pk, not null]
  ai_provider_id int [not null]

  name varchar [not null]
  api_key varchar [not null]
}

Table ai_model {
  id int [pk, not null]
  ai_provider_id int [not null]
  name varchar [not null]
}

Table agent_settings {
  agent_type varchar [pk, not null]

  ai_model_id int [not null]
  ai_credential_id int [not null]

  temperature decimal
  max_tokens int
}


Ref: "public"."ai_provider"."id" <? "public"."ai_model"."ai_provider_id"

Ref: "public"."ai_provider"."id" <? "public"."ai_credential"."ai_provider_id"

Ref: "public"."ai_credential"."id" <? "public"."agent_settings"."ai_credential_id"

Ref: "public"."ai_model"."id" <? "public"."agent_settings"."ai_model_id"

Ref: "public"."project_version"."project_id" ?> "public"."project"."id"

Ref: "project_version"."id" <? "evaluation"."project_version_id"

Ref: "evaluation"."id" <? "agent_execution"."evaluation_id"

Ref: "agent_execution"."agent_type" ?> "agent_settings"."agent_type"

Ref: "project"."selected_version_id" -? "project_version"."id"